# Github Workflow to Show the Github OIDC Integration with JFrog
name: "NodeJS:TODO MVC"
on: push

permissions:
  actions: read # For detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  security-events: write # Required for uploading code scanning
  attestations: write
  contents: read
env:
  WORKSPACE_TYPESCRIPT_REACT: "examples/typescript-react"
  BUILD_ID: "ga-${{github.run_number}}"
  RT_REPO_NPM_VIRTUAL: "todomvc-npm-virtual"
  RT_REPO_NPM_DEFAULT_LOCAL: "todomvc-npm-sandbox-local"
  RT_REPO_DOCKER_VIRTUAL: "todomvc-docker-virtual"
  RT_REPO_DOCKER_DEFAULT_LOCAL: "todomvc-docker-sandbox-local"
  EVIDENCE_JSON: "my-evidence.json"
jobs:
  npmPackage:
    name: "NPM Package"
    runs-on: ${{ matrix.os }}
    env: 
      BUILD_NAME: "todomvc-npm"
    defaults:
       run:
         working-directory: ${{env.WORKSPACE_TYPESCRIPT_REACT}}
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          oidc-provider-name: ${{ vars.JF_OIDC_PROVIDER_NAME }}

      - name: "Clone VCS"
        continue-on-error: true
        uses: actions/checkout@v4

      - name: "Config JF-CLI"
        run: |
          export JFROG_CLI_LOG_LEVEL=${{ env.JFROG_CLI_LOG_LEVEL }}
          pwd
          jf npmc --global --repo-resolve ${{ env.RT_REPO_NPM_VIRTUAL}} --repo-deploy ${{ env.RT_REPO_NPM_VIRTUAL}} 
          jf npm cache clean --force
          tree .

      - name: "Software version"
        continue-on-error: true
        run: |
          # JFrog CLI version
          jf --version
          # Ping the server
          jf rt ping
          # NodeJS
          node -v
          npm -v
          # Docker
          docker -v
          # jf config
          jf config show

      - name: "NPM: prestep summary"
        continue-on-error: true
        run: |
          jfcliv=`jf -v`
          nodeVer=`node -v`
          npmVer=`node -v`
          echo "# :frog: NPM Prestep Summary :pushpin:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " - Installed JFrog CLI [${jfcliv}](https://jfrog.com/getcli/) and [Node ${nodeVer} and NPM ${npmVer}](https://github.com/actions/setup-node) " >> $GITHUB_STEP_SUMMARY
          echo " - $(jf --version) " >> $GITHUB_STEP_SUMMARY
          echo " - Node $(node -v) " >> $GITHUB_STEP_SUMMARY
          echo " - NPM $(npm -v) " >> $GITHUB_STEP_SUMMARY
          echo " - Configured the JFrog Cli with SaaS Artifactory OIDC integration: ${{ vars.JF_OIDC_PROVIDER_NAME }} " >> $GITHUB_STEP_SUMMARY
          echo " - Variables info" >> $GITHUB_STEP_SUMMARY
          echo "    - ID: ${{env.BUILD_ID}} " >> $GITHUB_STEP_SUMMARY
          echo "    - Build Name: ${{env.BUILD_NAME}} " >> $GITHUB_STEP_SUMMARY
          echo "    - Repo URL: ${{env.RT_REPO_NPM_VIRTUAL}}" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

      - name: "Curation"  
        timeout-minutes: 15    
        continue-on-error: false    
        run: |
          jf ca --format=table --threads=100

      - name: "Audit: Xray & JAS" 
        timeout-minutes: 15  
        continue-on-error: false 
        run: |
          jf audit --npm --sast=true --sca=true --secrets=true --licenses=true --validate-secrets=true --vuln=true --format=table --extended-table=true --threads=100 --fail=false

      - name: "Package: npm Build"   # ref: https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/package-managers-integration#installing-npm-packages
        continue-on-error: false
        run: |
          jf npm install --build-name=${{ env.BUILD_NAME}} --build-number=${{ env.BUILD_ID}} 

      - name: "Xray: npm Artifact scan"
        timeout-minutes: 15  
        continue-on-error: true    
        run: |
          jf scan . --format=table --extended-table=true --threads=100 --fail=false

      - name: "Package: npm publish"
        continue-on-error: false
        run: |
          jf npm publish --build-name=${{ env.BUILD_NAME}} --build-number=${{ env.BUILD_ID}} 

      - name: "BCE: Collect env"
        continue-on-error: true
        run: jf rt bce ${{ env.BUILD_NAME}} ${{ env.BUILD_ID}} 
 
      - name: "BAG: Add VCS info"
        continue-on-error: true
        run: jf rt bag ${{ env.BUILD_NAME}} ${{ env.BUILD_ID}} 

      - name: "BP: Build Publish"   
        continue-on-error: false
        run: jf rt bp ${{ env.BUILD_NAME}} ${{ env.BUILD_ID}} --detailed-summary=true

      - name: "Evidence: Build Publish"
        continue-on-error: true 
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions","build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "Evidence-BuildPublish"}' > ./${{env.EVIDENCE_JSON}}
          cat ./${{env.EVIDENCE_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVIDENCE_JSON}} --predicate-type https://jfrog.com/evidence/build-signature/v1 --key "${{secrets.APP_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.APP_EVIDENCE_KEY_ALIAS}}
          echo "    - Evidence for BUILD Publish attached. " >> $GITHUB_STEP_SUMMARY





  dockerPackage:
    name: "Docker Package"
    runs-on: ubuntu-latest
    env: 
      BUILD_NAME: "todomvc-docker"
      DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64'
    defaults:
       run:
         working-directory: ${{env.WORKSPACE_TYPESCRIPT_REACT}}
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          oidc-provider-name: ${{ vars.JF_OIDC_PROVIDER_NAME }}

      - name: "Clone VCS"
        continue-on-error: true
        uses: actions/checkout@v4

      - name: "Docker: prestep-summary"
        run: |
          echo "# :frog: Docker: Prestep Summary :pushpin:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo "    - $(jf --version) " >> $GITHUB_STEP_SUMMARY
          echo "    - $(node -v) " >> $GITHUB_STEP_SUMMARY
          echo "    - $(npm -v) " >> $GITHUB_STEP_SUMMARY
          echo "    - $(docker -v) " >> $GITHUB_STEP_SUMMARY
          echo " - Docker buildx configured with platforms: [${{env.DOCKER_BUILDX_PLATFORMS}}](https://docs.docker.com/reference/cli/docker/buildx/create/#platform) " >> $GITHUB_STEP_SUMMARY
          echo " - Configured the JFrog Cli and Docker login with SaaS Artifactory OIDC integration  " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " - Variables info" >> $GITHUB_STEP_SUMMARY
          echo "    - ID: ${{env.BUILD_ID}} " >> $GITHUB_STEP_SUMMARY
          echo "    - Build Name: ${{env.BUILD_NAME}} " >> $GITHUB_STEP_SUMMARY
          echo "    - Docker Repo URL: ${{env.RT_REPO_DOCKER_VIRTUAL}}" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
        
            


  

  yarnPackage:
    name: "Yarn Package"
    runs-on: ubuntu-latest
    env: 
      BUILD_NAME: "todomvc-yarn"
      BUILD_ID: "ga-${{github.run_number}}"
      RT_REPO_NPM_VIRTUAL: "todomvc-npm-virtual"
      RT_REPO_NPM_DEFAULT_LOCAL: "todomvc-npm-sandbox-local"
    defaults:
       run:
         working-directory: ${{env.WORKSPACE_TYPESCRIPT_REACT}}
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          oidc-provider-name: ${{ vars.JF_OIDC_PROVIDER_NAME }}
      - name: "Clone VCS"
        continue-on-error: true
        uses: actions/checkout@v4

